trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  GRADLE_OPTS: '-Xmx3072m'

steps:
- task: Gradle@3
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    tasks: 'clean build test'
    options: '--refresh-dependencies --stacktrace --info'
