trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Ensure gradlew is executable
- script: chmod +x gradlew
  displayName: Make gradlew executable

# Run Gradle build
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'clean build test'
    options: '--refresh-dependencies --stacktrace --info -Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/build/test-results/test/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
